"""
Directory path constants for the Landsat 8 Cloud/Shadow/Snow Detection project.
Adjust these paths to match your data layout.
"""

import os

# Project root (src/ directory)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Data directories
WEDDELL_SEA_SOURCE_PATH = '/earth00_home/immj/Landsat/USGS/OLI_TIRS/lv1/Weddell_Sea'
DATA_ROOT = os.path.join(PROJECT_ROOT, 'data')

# Raw Landsat 8 .SAFE-style directories (containing per-band TIF files)
TRAIN_SAFE_PATH = os.path.join(DATA_ROOT, 'TRAIN')
VALID_SAFE_PATH = os.path.join(DATA_ROOT, 'VALIDATION')
PRED_PATH = os.path.join(DATA_ROOT, 'TEST')

# HDF5 patch directories (generated by make_landsat_data.py)
TRAIN_PATH = os.path.join(DATA_ROOT, 'TRAIN_H5')
VALID_PATH = os.path.join(DATA_ROOT, 'VALIDATION_H5')

# Experiment data directory (models, logs)
EXP_DATA_PATH = os.path.join(PROJECT_ROOT, 'exp_data')

# Ensure critical directories exist
for _dir in [TRAIN_SAFE_PATH, VALID_SAFE_PATH, PRED_PATH,
             TRAIN_PATH, VALID_PATH, EXP_DATA_PATH]:
    os.makedirs(_dir, exist_ok=True)
